### ISSUE TITLE
size this down 

### ISSUE THREAD

**Issue by TylerAustinW** [Connor-Goodall/Connor-Goodall.github.io#1]
@Connor-Goodall 

https://github.com/Connor-Goodall/Connor-Goodall.github.io/blob/2ce9536921cfcc9c01b90f22da9dd3b48e410f8c/styles.css#L87

need to size this down to at least 30%

```css
.about-img {
    height: auto;
    max-width: 30%;
}
```

![image](https://user-images.githubusercontent.com/63419902/216802829-4ed4e33e-0da8-4046-b5e5-a0a3fd4560d6.png)
